#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

rm -rf 0
cp -r 0.orig 0

runApplication blockMesh
runApplication setFields
runApplication decomposePar
runApplication mpirun -np 8 twoLiquidMixingFoam -parallel

#------------------------------------------------------------------------------
